# Generated by Django 3.2.3 on 2021-07-03 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('rutColaborador', models.IntegerField(primary_key=True, serialize=False, verbose_name='Rut de Colaborador')),
                ('nomColaborador', models.CharField(max_length=60, verbose_name='Nombre de Colaborador')),
                ('fonoColaborador', models.IntegerField(verbose_name='Teléfono de Colaborador')),
                ('dirColaborador', models.CharField(max_length=60, verbose_name='Dirección de Colaborador')),
                ('emailColaborador', models.EmailField(max_length=254, verbose_name='Email de Colaborador')),
                ('paisColaborador', models.CharField(max_length=20, verbose_name='Pais de Colaborador')),
                ('contrasenaColaborador', models.CharField(max_length=20, verbose_name='Contraseña de Colaborador')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='img/')),
            ],
        ),
    ]
